name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: docker-compose build

      - name: Upload image
        uses: ishworkh/docker-image-artifact-upload@v1
        with:
          image: "xpay_server:latest"

  lint:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      - name: Download image
        uses: ishworkh/docker-image-artifact-download@v1
        with:
          image: "xpay_server:latest"

      - name: Lint
        run: docker-compose run server ./lint.sh

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      - name: Download image
        uses: ishworkh/docker-image-artifact-download@v1
        with:
          image: "xpay_server:latest"

      - name: Test
        run: docker-compose run server ./test.sh
  
  delete-artifact:
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: ${{ github.event_name != 'push' }}

    steps:
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: "action_image_artifact_xpay_server_latest"

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: ${{ github.event_name == 'push' }}

    steps:
      - name: Delete Artifact
        uses: geekyeggo/delete-artifact@v1
        with:
          name: "action_image_artifact_xpay_server_latest"
      - run: echo "AWS integration not setup" && exit 1
